config/routes.rb
Fandangr::Application.routes.draw do

  get "reservations/create"
	get "/reservations/get_values" => "reservations#get_values"

  get "/all" => "static_pages#all"
	root :to => 'static_pages#index'
	
	resources :movies
	resources :users
	resources :schedules
	resources :rooms
	resources :sessions
	resources :reservations

	get "/logout" => 'sessions#destroy', as:"logout"
	
	get "/admin" => "admins#panel", as:"admin"

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  attr_accessible :description, :name, :duration, :plot, :rating
	
	has_many :schedules

	has_many :reservations, through: :schedules

	validates :name,
		presence:true,
		uniqueness:true

	validates :duration,
		presence:true,
		numericality:{greater_than:0}

  before_save :update_duration
	def playing_at
		schedules = Schedule.where("movie_id = ? AND start_time > ? AND start_time < ? ", self.id, Time.now, Time.now+2*7*24*60*60)
	end
	
	def update_duration
		update_imdb
	  self.duration *= 60
	end
	#def duration=(value)
	#  self.duration = value*60
	#end


	def update_imdb 
		@movies_imdb = Movies::find_by_title(self.name)
		self.duration = @movies_imdb.runtime
		self.name = @movies_imdb.title
		self.description = @movies_imdb.plot
		self.rating = get_rating(@movies_imdb)
		self.poster = @movies_imdb.poster
	end

	def get_rating(movie)
		initial = /imdbRating\"=>\"[0-9]\.[0-9]\"/.match(movie.inspect)[0]
		regex = /[0-9]\.[0-9]/.match(initial)
		return regex
	end
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :schedule
  belongs_to :seat
  # attr_accessible :title, :body
  
  def is_valid_seat? seat
   self.schedule.reservations.each do |reservation|
     if reservation.seat.pos_x == seat.pos_x && reservation.seat.pos_y == seat.pos_y
       return false
     end
   end
   return true
  end
end

app/models/room.rb
class Room < ActiveRecord::Base
  attr_accessible :name
  
  has_many :seats, dependent: :destroy
	has_many :schedules

	validates :name,
		presence:true,
		uniqueness:true
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :movie
  belongs_to :room
  has_many :reservations

	attr_accessible :start_time, :end_time, :movie_id, :room_id

	validates :start_time,
		presence:true

	validates :end_time,
		presence:true

	validates :movie,
		presence:true

	validates :room,
		presence:true

	validate :no_overlap 

	def self.showing(num_weeks=2)
		schedules = Schedule.where("start_time > ? AND start_time < ? ", Time.now, Time.now+2*7*24*60*60)
	end


	def display_starting_time 
		self.start_time.to_s(:playing_at)
	end
	def display_end_time 
		self.end_time.to_s(:playing_at)
	end

	def start_time=(value)
		write_attribute :start_time, value 
		write_attribute :end_time, value + movie.duration
	end

	def no_overlap
		schedules = Schedule.where("room_id = ?", room.id)
		schedules.each do |schedule|
			#if start_time > schedule.start_time && start_time < schedule.end_time
			#	errors.add(:start_time, "Start time overlaps")
			#end
			#if end_time > schedule.start_time && end_time < schedule.end_time
			#	errors.add(:end_time, "End time overlaps")
			#end

			if (start_time..end_time).overlaps?(schedule.start_time..schedule.end_time)
				errors.add(:start_time, "Time are overlapping")
			end
			
		end
	end


end

app/models/seat.rb
class Seat < ActiveRecord::Base
  belongs_to :room
  
  attr_accessible :pos_x, :pos_y

	validates :pos_x,
		presence:true,
		numericality:{greater_than_or_equal_to:0}

	validates :pos_y,
		presence:true,
		numericality:{greater_than_or_equal_to:0}
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	has_many :reservations
	has_many :schedules, through: :reservations
	has_many :movies, through: :schedules

  attr_accessible :password_confirmation, :password, :uun

	validates :uun,
		presence:true,
		uniqueness:true

  def uun=(value)
    write_attribute :uun, value.downcase
  end
  
  def admin?
    return self.is_admin
  end


end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  
  def panel
    if current_user.admin?
      @movie = Movie.new
      @schedule = Schedule.new
    else
      flash[:alert] = "Good try, but you're not an admin"
      redirect_to root_path
    end
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def new
		@movie = Movie.new
  end

  def create
		@movie = Movie.new(params[:movie])
		
		if @movie.save
		  redirect_to root_path
    else
      render :new
    end
  end

  def update
  end

  def destroy
  end

  def edit
  end


end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def new
		@room = Room.new
  end

  def create
		@room = Room.create(params[:room])
		redirect_to root_path
  end

  def edit
		redirect_to root_path
  end

  def destroy
		redirect_to root_path
  end

  def update
		redirect_to root_path
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  
  skip_before_filter :require_authentication, only:[:show]
  
  def new
		@schedule = Schedule.new
  end

  def create
		@schedule = Schedule.new(params[:schedule])
		if @schedule.save
			redirect_to root_path
		else
			render :new
		end
  end

	def show
		@schedule = Schedule.find(params[:id])
		@room = @schedule.room
	end

  def update
  end

  def destroy
  end

  def edit
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  skip_before_filter :require_authentication, only:[:create, :destroy]
  
  def create
    user = User.find_by_uun(params[:uun])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "You just logged in, welcome #{user.uun}"
      redirect_to user_path(user)
    else
      flash[:alert] = "Username or password invalid"
      redirect_to root_path
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path, :notice => "You are now logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_filter :require_authentication, only:[:new, :create]
  def new
		@user = User.new
  end

  def create
		@user = User.create(params[:user])
		session[:user_id] = @user.id
		redirect_to root_path
  end

  def edit
		redirect_to root_path
  end
	
	def show
		@my_hash = {}

		current_user.reservations.each do |reservation|
			@my_hash[reservation.schedule_id] = [Schedule.find(reservation.schedule_id).movie, Reservation.where("schedule_id = ? AND user_id = ?", reservation.schedule_id, current_user.id).count, Schedule.find(reservation.schedule_id)]
		end
	end

  def destroy
		redirect_to root_path
  end

  def update
		redirect_to root_path
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/panel.html.haml
.row
  .span12
    %h1 
      Admin Panel
      
    = render partial:"movies/form"  
      
    = render partial:"schedules/form"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Movie Theatre
    //%link{href:"//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css", rel:"stylesheet"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .container
      .row
        .span12
          .navbar
            %nav.navbar-inner
              %ul.nav
                
              - if !current_user
                %a{href:new_user_path}
                  .btn.pull-right
                    Signup
                = form_tag sessions_path, class:"navbar-form pull-right" do
                  = text_field_tag :uun, params[:uun], placeholder:"Username", class:"span2"
                  = password_field_tag :password, params[:password], type:"password", placeholder:"Password", class:"span2"
                  = submit_tag :Login, :class => "btn"
                
              - else
                .btn
                  = link_to "My Tickets", "/users/#{current_user.id}"
                .btn
                  = link_to "Upcoming Movies", "/"
                
                - if current_user.admin?
                  .btn
                    = link_to "Admin", admin_path
                .pull-right 
                  Hello
                  = current_user.uun.capitalize
                  .btn
                    = link_to "Logout", logout_path
      .row
        .span12
      
          - unless flash[:notice].blank?
            .alert
              = flash[:notice]
          - unless flash[:alert].blank?
            .alert.alert-error  
              = flash[:alert]
            
      = yield